import { readFileSync } from "node:fs"
import { describe, expect, it } from "vitest"

const read = (path: string) => readFileSync(path, "utf8")

describe("manual UI review fixes", () => {
  it("keeps failed runs failed and renders their provider error inline", () => {
    const activeChat = read("src/renderer/features/agents/main/active-chat.tsx")
    expect(activeChat).toContain('setStatus(subChatId, "error")')
    expect(activeChat).toContain('status === "error"')
    expect(activeChat).toContain("presentRunError")
    expect(activeChat).toContain("technicalDetail")
  })

  it("uses a compact transcript rail without a ready status capsule", () => {
    const overview = read("src/renderer/features/agents/main/chat-transcript-overview.tsx")
    expect(overview).toContain('aria-label="Transcript timeline"')
    expect(overview).toContain("totalTurns <= 3")
    expect(overview).toContain("h-4 w-7")
    expect(overview).toContain("group-hover/marker:block")
    expect(overview).toContain("left-0")
    expect(overview).toContain("hover:bg-popover")
    expect(overview).toContain("group-hover/timeline:opacity-100")
    expect(overview).toContain("promptPreview")
    expect(overview).not.toContain("right-1.5")
    expect(overview).not.toContain("ProgressCapsule")
    expect(overview).not.toContain("Popover")
  })

  it("keeps floating prompts out of transformed virtual groups", () => {
    const messages = read("src/renderer/features/agents/main/isolated-messages-section.tsx")
    expect(messages).toContain("top: `${virtualItem.start - scrollMargin}px`")
    expect(messages).not.toContain("transform: `translateY(${virtualItem.start")
  })

  it("shows lightweight in-transcript startup feedback and a real load state", () => {
    const activeChat = read("src/renderer/features/agents/main/active-chat.tsx")
    expect(activeChat).toContain('const STREAMING_WORDS = ["Thinking", "Working", "Cooking"]')
    expect(activeChat).toContain("Loading chat…")
    expect(activeChat).toContain("refetchOnMount: false")
    expect(activeChat).not.toContain('refetchOnMount: "always"')
  })

  it("expands long user messages inline instead of opening a dialog", () => {
    const userMessage = read("src/renderer/features/agents/ui/agent-user-message-bubble.tsx")

    expect(userMessage).toContain('aria-label={isExpanded ? "Collapse message" : "Expand message"}')
    expect(userMessage).toContain("aria-expanded={isExpanded}")
    expect(userMessage).toContain('isExpanded ? "max-h-none" : "max-h-[100px]"')
    expect(userMessage).toContain('isExpanded && "rotate-90"')
    expect(userMessage).not.toContain("Full message")
    expect(userMessage).not.toContain("bg-gradient-to-t")
  })

  it("provides native-feeling paste and mouse-back navigation", () => {
    const editor = read("src/renderer/features/agents/mentions/agents-mentions-editor.tsx")
    const layout = read("src/renderer/features/layout/agents-layout.tsx")
    expect(editor).toContain("navigator.clipboard")
    expect(editor).toContain("Paste")
    expect(layout).toContain("event.button !== 3")
    expect(layout).toContain("moveInNavigationHistory")
  })

  it("keeps Quick access available without empty built-in categories", () => {
    const sidebar = read("src/renderer/features/sidebar/agents-sidebar.tsx")
    expect(sidebar).toContain('title="Quick access"')
    expect(sidebar).toContain('title: "Pinned"')
    expect(sidebar).toContain('title: "Starred"')
    expect(sidebar).toContain("drafts.length > 0")
    expect(sidebar).not.toContain("No drafts")
    expect(sidebar).not.toContain("flapstackAppIcon")
  })

  it("uses compact per-pane tabs without labelling every pane as a group", () => {
    const workbench = read("src/renderer/features/agents/workbench/chat-workbench.tsx")
    const content = read("src/renderer/features/agents/ui/agents-content.tsx")
    expect(workbench).toContain("h-[34px] w-40 shrink-0")
    expect(content.match(/h-\[34px\] w-40 shrink-0/g)).toHaveLength(5)
    expect(workbench).toContain("chatId === activeChatId")
    expect(workbench).toContain(': "transparent"')
    expect(workbench).toContain("data-chat-tab-accent")
    expect(workbench).toContain("inset-x-1 -top-px h-px")
    expect(workbench).toContain("group-hover/tab:opacity-100")
    expect(workbench).toContain("data-chat-pane-scrollbar")
    expect(workbench).toContain("data-chat-unseen-indicator")
    expect(content).toContain("data-open-chat-unseen-indicator")
    expect(content).toContain("data-group-unseen-indicator")
    expect(workbench).not.toContain("groupPresentation.collapsed")
    expect(content).toContain("data-workbench-navigation-group")
    expect(content).not.toContain("data-active-group-indicator")
    expect(content).toContain('? "border-2 border-foreground/50')
    expect(content).not.toContain("rounded-t-md border border-b-0")
    expect(content).toContain("Rename group…")
  })

  it("uses group color on the icon and selected outline while project color stays on Chats", () => {
    const content = read("src/renderer/features/agents/ui/agents-content.tsx")
    const workbench = read("src/renderer/features/agents/workbench/chat-workbench.tsx")
    expect(content).not.toContain("resolveGroupTabBackground")
    expect(content).toContain("if (!color || !isActive) return undefined")
    expect(content).toContain("border-transparent bg-transparent")
    expect(content).toContain("data-group-color-icon")
    expect(content).toContain("GROUP_COLOR_SWATCHES[group.color]")
    expect(content.match(/readStoredProjectColorValues\(\)/g)).toHaveLength(4)
    expect(content).not.toContain("borderTopColor: group.color")
    expect(content).toContain("border-foreground/20 bg-muted")
    expect(content).toContain("text-foreground/90")
    expect(content).toContain("text-foreground/80")
    expect(workbench).toContain("borderColor: chatAccents.get(activeChatId) ?? undefined")
    expect(content).not.toContain('borderTopColor: isActive ? underlineColor : "transparent"')
    expect(content).toContain("{ borderColor: underlineColor }")
    expect(content).toContain('{ borderTopColor: "transparent" }')
    expect(content).toContain("data-chat-tab-accent")
    expect(content).toContain("inset-x-1 -top-px h-px")
    expect(workbench).not.toContain("data-active-screen-indicator")
  })

  it("opens an editable dialog when renaming a group", () => {
    const content = read("src/renderer/features/agents/ui/agents-content.tsx")
    expect(content).toContain("<RenameDialog")
    expect(content).toContain("setRenamingWorkbenchGroup")
    expect(content).not.toContain('window.prompt("Group name"')
  })

  it("keeps completed Chats unseen until an explicit Chat or pane interaction", () => {
    const activeChat = read("src/renderer/features/agents/main/active-chat.tsx")
    const content = read("src/renderer/features/agents/ui/agents-content.tsx")
    expect(activeChat.match(/markChatUnseen\(current, chatId\)/g)).toHaveLength(2)
    expect(activeChat).toContain("if (workbenchActive !== undefined) return")
    expect(content).toContain("handleChatViewed")
    expect(content).toContain("markChatSeen(current, chatId)")
  })

  it("routes sidebar Chat clicks through group-aware workbench selection", () => {
    const sidebar = read("src/renderer/features/sidebar/agents-sidebar.tsx")
    const content = read("src/renderer/features/agents/ui/agents-content.tsx")
    expect(sidebar).toContain("CHAT_WORKBENCH_SELECT_CHAT_EVENT")
    expect(content).toContain("CHAT_WORKBENCH_SELECT_CHAT_EVENT")
    expect(content).toContain("showSelectedChatLayout(chatId)")
    expect(sidebar).not.toContain("CHAT_WORKBENCH_OPEN_SINGLE_EVENT")
    expect(content).not.toContain("CHAT_WORKBENCH_OPEN_SINGLE_EVENT")
  })

  it("uses enter and reorder zones across ordinary Chats and groups", () => {
    const content = read("src/renderer/features/agents/ui/agents-content.tsx")
    expect(content).toContain("resolveTopNavigationDropIntent")
    expect(content).toContain("resolveTopNavigationReorderIntent")
    expect(content).toContain("resolveChatWorkbenchNavigationItems")
    expect(content).toContain("reorderChatWorkbenchNavigationItem")
    expect(content).toContain('data-top-navigation-item-kind="group"')
    expect(content).toContain('data-top-navigation-item-kind="chat"')
    expect(content).toContain("renameChatWorkbenchGroup")
    expect(content).toContain("TOP_NAVIGATION_ENTER_DELAY_MS")
    expect(content).toContain("topNavigationEnterTimerRef")
    expect(content).toContain("data-chat-main-bar-drop-target")
    expect(content).toContain("moveGroupedChatToMainBar")
    expect(content).toContain("appendChatWorkbenchNavigationItem")
    expect(content).not.toContain("event.target !== event.currentTarget")
    expect(content).toContain("workbenchChats")
    expect(content).toContain("renderWorkbenchChat")
    expect(content).toContain("handleWorkbenchActiveChatChange")
    expect(content).not.toContain("handleOpenChatTabPointerDown")
  })

  it("offers durable group organization and shared workbench history", () => {
    const content = read("src/renderer/features/agents/ui/agents-content.tsx")
    const workbench = read("src/renderer/features/agents/workbench/chat-workbench.tsx")
    const titleBar = read("src/renderer/components/windows-title-bar.tsx")
    expect(content).toContain("CHAT_WORKBENCH_GROUP_COLORS.map")
    expect(content).toContain("Group color")
    expect(content).toContain("Keep this one-Chat group?")
    expect(content).toContain("handleMoveChatToWorkbenchGroup")
    expect(content).toContain("handleCreateWorkbenchGroupFromChat")
    expect(content).toContain("recordAppAction")
    expect(content).toContain("restoreWorkbenchSnapshot")
    expect(titleBar).toContain("undoAppAction")
    expect(titleBar).toContain("redoAppAction")
    expect(titleBar).toContain("event.stopImmediatePropagation()")
    expect(workbench).toContain("Add to new group")
    expect(workbench).toContain("Main bar")
  })

  it("keeps the measured bottom dock clear of the transcript scrollbar", () => {
    const activeChat = read("src/renderer/features/agents/main/active-chat.tsx")
    expect(activeChat).toContain("data-chat-bottom-dock")
    expect(activeChat).toContain("--chat-bottom-dock-height")
    expect(activeChat).toContain("absolute bottom-0 left-0 right-3 z-20")
    expect(activeChat).toContain("calc(var(--chat-bottom-dock-height")
  })
})
