import type { DevMcpToolDefinition, DevMcpToolName } from "./types"

export const devMcpTestControlTools: DevMcpToolDefinition[] = [
  {
    name: "get_test_environment",
    description: "Report local app, database, runtime, and repository diagnostics for E2 testing.",
    tier: 0,
    mutates: false,
    status: "implemented",
  },
  {
    name: "get_harness_status",
    description: "Report Codex and Claude readiness without returning secrets.",
    tier: 0,
    mutates: false,
    status: "implemented",
  },
  {
    name: "get_provider_status",
    description: "Report OpenRouter and NanoGPT readiness and available model counts.",
    tier: 0,
    mutates: false,
    status: "implemented",
  },
  {
    name: "get_credential_status",
    description: "Inspect managed credential status without returning plaintext.",
    tier: 0,
    mutates: false,
    status: "implemented",
  },
  {
    name: "set_or_replace_credential",
    description: "Set or replace one managed credential through the production write-only service.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "migrate_legacy_credential",
    description:
      "Attempt one acknowledged legacy credential migration without returning plaintext.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "remove_credential",
    description: "Remove one managed credential and return redacted status.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "get_settings_state",
    description:
      "Inspect the Settings release registry, search results, provider scope, and stable targets.",
    tier: 0,
    mutates: false,
    status: "implemented",
  },
  {
    name: "control_settings",
    description:
      "Open, close, navigate, search, or select a project in the live Settings renderer.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "get_settings_legacy_state",
    description: "Inspect raw and release-effective legacy Settings state in the live renderer.",
    tier: 0,
    mutates: false,
    status: "implemented",
  },
  {
    name: "mutate_settings_legacy_state",
    description: "Seed bounded legacy tab and quick-switch values for release-behavior proof.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "get_visible_copy_search_state",
    description:
      "Inspect bounded visible chat copy/search text without private tool or attachment payloads.",
    tier: 0,
    mutates: false,
    status: "implemented",
  },
  {
    name: "select_test_chat",
    description: "Select one active persisted test chat in the live renderer by exact IDs.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "copy_test_chat_history",
    description:
      "Exercise active-header or sidebar-menu full-history copy and return bounded clipboard proof.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "get_renderer_orchestration_state",
    description: "Inspect bounded visible orchestration task-card, lineage, and selection state.",
    tier: 0,
    mutates: false,
    status: "implemented",
  },
  {
    name: "get_shortcut_state",
    description:
      "Inspect live resolved shortcut bindings and diagnostics without renderer secrets.",
    tier: 0,
    mutates: false,
    status: "implemented",
  },
  {
    name: "get_product_mcp_renderer_state",
    description: "Inspect bounded live product-MCP renderer state for one isolated test caller.",
    tier: 0,
    mutates: false,
    status: "implemented",
  },
  {
    name: "cancel_product_mcp_child_run",
    description: "Cancel one spawned Codex or Claude child owned by an isolated test caller.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "control_product_mcp_renderer",
    description: "Open or close the audit surface for one isolated product-MCP test caller.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "mutate_shortcut_binding",
    description: "Set or reset one live shortcut through production preference persistence.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "list_provider_extensions",
    description:
      "List provider-scoped extension identities and capabilities without returning extension content.",
    tier: 0,
    mutates: false,
    status: "implemented",
  },
  {
    name: "list_test_targets",
    description: "List projects, chats, sub-chats, worktree paths, and recent message counts.",
    tier: 0,
    mutates: false,
    status: "implemented",
  },
  {
    name: "get_chat_state",
    description: "Inspect one chat transcript, run state, tools, and approvals without secrets.",
    tier: 0,
    mutates: false,
    status: "implemented",
  },
  {
    name: "get_run_state",
    description: "Inspect one persisted agent run and its matching assistant metadata.",
    tier: 0,
    mutates: false,
    status: "implemented",
  },
  {
    name: "get_reasoning_timer_state",
    description: "Inspect the authoritative live or completed reasoning timer for one run.",
    tier: 0,
    mutates: false,
    status: "implemented",
  },
  {
    name: "get_voice_state",
    description: "Inspect bounded production Voice settings, adapters, models, and history counts.",
    tier: 0,
    mutates: false,
    status: "implemented",
  },
  {
    name: "control_voice_settings",
    description: "Update bounded production Voice preferences without synthetic UI input.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "create_voice_ui_fixture",
    description: "Create one sanitized local Voice History row with a silent WAV.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "cleanup_voice_ui_fixture",
    description: "Delete one exact sanitized Stage 3 Voice History fixture.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "get_renderer_voice_ui_state",
    description: "Inspect bounded Voice settings, history rows, and mounted actions.",
    tier: 0,
    mutates: false,
    status: "implemented",
  },
  {
    name: "control_renderer_voice_ui",
    description: "Exercise bounded Voice settings, history, preview, and stop controls.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "get_usage_state",
    description:
      "Inspect redacted Usage settings, provider states, current samples, and daemon health.",
    tier: 0,
    mutates: false,
    status: "implemented",
  },
  {
    name: "refresh_usage_state",
    description: "Run the production manual Usage refresh with saved credentials only.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "create_usage_ui_fixture",
    description: "Create sanitized Usage UI evidence rows without credentials or network calls.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "cleanup_usage_ui_fixture",
    description: "Delete only the sanitized Stage 3 Usage UI evidence rows.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "get_renderer_usage_ui_state",
    description: "Inspect bounded provider filters, history controls, paging, and row counts.",
    tier: 0,
    mutates: false,
    status: "implemented",
  },
  {
    name: "control_renderer_usage_ui",
    description: "Exercise enumerated provider, history, monitoring, and paging controls.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "get_run_change_state",
    description: "Inspect a stored run change set and optional historical review diff.",
    tier: 0,
    mutates: false,
    status: "implemented",
  },
  {
    name: "undo_run_change",
    description: "Undo one stored run change set through the production conflict-safe service.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "create_carryover_run_fixture",
    description:
      "Create an isolated temp-repo run with two stored file changes and reasoning output.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "get_carryover_run_fixture_files",
    description: "Read only the two bounded text files owned by an isolated carryover fixture.",
    tier: 0,
    mutates: false,
    status: "implemented",
  },
  {
    name: "cleanup_carryover_run_fixture",
    description: "Delete one isolated carryover fixture database row and temp Git repository.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "get_renderer_carryover_state",
    description: "Inspect bounded live Voice, Usage, reasoning, or run-change renderer state.",
    tier: 0,
    mutates: false,
    status: "implemented",
  },
  {
    name: "capture_test_renderer",
    description:
      "Capture a mode-0600 local PNG of the selected checkout or carryover test renderer.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "cleanup_test_renderer_capture",
    description: "Delete one exact temporary renderer capture created by this process.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "control_renderer_carryover",
    description: "Control an enumerated live reasoning or run-change disclosure action.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "list_pending_approvals",
    description: "List pending OpenRouter or NanoGPT permission requests.",
    tier: 0,
    mutates: false,
    status: "implemented",
  },
  {
    name: "get_opencode_logs",
    description: "Read a bounded redacted tail of isolated provider runtime logs.",
    tier: 0,
    mutates: false,
    status: "implemented",
  },
  {
    name: "prepare_product_mcp_caller",
    description: "Create an isolated Codex or Claude caller fixture for live product-MCP tests.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "set_product_mcp_exposure",
    description: "Enable or disable product MCP exposure for one test caller chat.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "start_product_mcp_call",
    description: "Start one real product stdio MCP call and return a pollable test call ID.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "get_product_mcp_call",
    description: "Read the bounded result of one product stdio MCP test call.",
    tier: 0,
    mutates: false,
    status: "implemented",
  },
  {
    name: "reply_product_mcp_approval",
    description: "Approve or deny one pending product MCP test invocation.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "get_product_mcp_state",
    description: "Read exposure, approvals, audit, lineage, and run truth for one caller chat.",
    tier: 0,
    mutates: false,
    status: "implemented",
  },
  {
    name: "manage_product_mcp_recovery",
    description: "List or explicitly resolve product MCP terminal-audit recovery claims.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "cleanup_product_mcp_caller",
    description: "Cancel and archive one isolated product-MCP caller fixture after testing.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "list_agent_input_requests",
    description: "List provider-neutral input requests currently owned by the live app.",
    tier: 0,
    mutates: false,
    status: "implemented",
  },
  {
    name: "get_renderer_agent_input_state",
    description: "Inspect active renderer question ownership and dialog visibility.",
    tier: 0,
    mutates: false,
    status: "implemented",
  },
  {
    name: "get_renderer_agent_input_navigation_state",
    description: "Inspect selected chat and bounded background-input badge counts.",
    tier: 0,
    mutates: false,
    status: "implemented",
  },
  {
    name: "navigate_agent_input_notification",
    description: "Exercise exact pending-request notification navigation in the renderer.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "ensure_test_project",
    description: "Register or restore the active development checkout as a local test project.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "archive_test_project",
    description: "Reversibly archive an idle test project for the active development checkout.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "create_test_chat",
    description:
      "Create one local project chat and its canonical conversation for provider testing.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "open_test_chat",
    description: "Select one existing test chat in the live renderer without synthetic UI input.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "archive_test_task",
    description: "Reversibly archive one test task and every idle linked chat.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "archive_test_chat",
    description: "Reversibly archive one idle test chat without deleting its history.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "mutate_project_provider_extension",
    description:
      "Create, update, or delete one project-scoped provider extension through the production adapter.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "get_permission_state",
    description: "Inspect permission defaults and optional resolved chat custom capabilities.",
    tier: 0,
    mutates: false,
    status: "implemented",
  },
  {
    name: "set_permission_default",
    description: "Set the production global permission default with explicit custom capabilities.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "set_permission_change_behavior",
    description:
      "Set Ask, all-chat, or current-chat permission behavior through production persistence.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "set_chat_permission",
    description: "Set one chat or all chats permission mode through production synchronization.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "preview_permission",
    description: "Preview exact harness permission mapping without executing a provider.",
    tier: 0,
    mutates: false,
    status: "implemented",
  },
  {
    name: "get_permission_ui_state",
    description: "Inspect the active chat permission selector and confirmation state.",
    tier: 0,
    mutates: false,
    status: "implemented",
  },
  {
    name: "control_permission_ui",
    description:
      "Drive the mounted permission selector and confirmation through typed renderer actions.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "set_chat_run_config",
    description: "Persist a test run configuration hint for a sub-chat.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "send_test_prompt",
    description:
      "Append a database-only test prompt for legacy fixture setup; does not launch a run.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "launch_test_run",
    description: "Launch a real Cursor, OpenRouter, or NanoGPT run through the app runtime.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "launch_harness_test_run",
    description: "Launch a real Codex or Claude run rooted to the selected persisted test project.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "list_codex_permission_requests",
    description: "List redacted pending Codex ACP permission requests and exact response options.",
    tier: 0,
    mutates: false,
    status: "implemented",
  },
  {
    name: "reply_codex_permission_request",
    description:
      "Resolve one pending Codex ACP permission request with an exact advertised option.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "inject_agent_input_request",
    description: "Inject one bounded provider-neutral input request into a live test chat.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "reply_agent_input_request",
    description: "Answer, skip, or cancel one injected provider-neutral input request.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "reply_approval",
    description: "Reply once to a pending provider permission request.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "cancel_run",
    description: "Cancel a matching active OpenRouter or NanoGPT run.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "wait_for_run",
    description: "Poll a sub-chat until an assistant reply appears or timeout expires.",
    tier: 0,
    mutates: false,
    status: "implemented",
  },
  {
    name: "verify_run_artifacts",
    description: "Verify persisted assistant reply and no-edit expectations for a sub-chat.",
    tier: 0,
    mutates: false,
    status: "implemented",
  },
  {
    name: "run_project_check",
    description: "Run npm check with the known-good bundled Node runtime when present.",
    tier: 2,
    mutates: false,
    status: "implemented",
  },
  {
    name: "openspec_validate",
    description: "Run strict OpenSpec validation for the active Stage 1 change.",
    tier: 2,
    mutates: false,
    status: "implemented",
  },
  {
    name: "create_test_orchestration_fixture",
    description:
      "Create a read-only Codex or Claude project-chat fixture for orchestration testing.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "create_test_orchestration",
    description: "Create or attach a durable local orchestration through the production service.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
  {
    name: "get_test_orchestration",
    description: "Read a durable orchestration overview and lineage for functional proof.",
    tier: 0,
    mutates: false,
    status: "implemented",
  },
  {
    name: "mutate_test_orchestration",
    description: "Tick, control, progress, retry, replace, or add a test orchestration agent.",
    tier: 1,
    mutates: true,
    status: "implemented",
  },
]

export function getDevMcpTool(name: string): DevMcpToolDefinition | null {
  return devMcpTestControlTools.find((tool) => tool.name === name) ?? null
}

export const devMcpExposedToolNames = [
  "get_test_environment",
  "get_harness_status",
  "get_provider_status",
  "get_credential_status",
  "set_or_replace_credential",
  "migrate_legacy_credential",
  "remove_credential",
  "get_settings_state",
  "control_settings",
  "get_settings_legacy_state",
  "mutate_settings_legacy_state",
  "get_visible_copy_search_state",
  "select_test_chat",
  "copy_test_chat_history",
  "get_renderer_orchestration_state",
  "get_shortcut_state",
  "mutate_shortcut_binding",
  "list_provider_extensions",
  "list_test_targets",
  "get_chat_state",
  "get_run_state",
  "get_reasoning_timer_state",
  "get_voice_state",
  "control_voice_settings",
  "create_voice_ui_fixture",
  "cleanup_voice_ui_fixture",
  "get_renderer_voice_ui_state",
  "control_renderer_voice_ui",
  "get_usage_state",
  "refresh_usage_state",
  "create_usage_ui_fixture",
  "cleanup_usage_ui_fixture",
  "get_renderer_usage_ui_state",
  "control_renderer_usage_ui",
  "get_run_change_state",
  "undo_run_change",
  "create_carryover_run_fixture",
  "get_carryover_run_fixture_files",
  "cleanup_carryover_run_fixture",
  "get_renderer_carryover_state",
  "control_renderer_carryover",
  "list_pending_approvals",
  "get_opencode_logs",
  "prepare_product_mcp_caller",
  "set_product_mcp_exposure",
  "start_product_mcp_call",
  "get_product_mcp_call",
  "reply_product_mcp_approval",
  "get_product_mcp_state",
  "get_product_mcp_renderer_state",
  "control_product_mcp_renderer",
  "manage_product_mcp_recovery",
  "cleanup_product_mcp_caller",
  "cancel_product_mcp_child_run",
  "list_agent_input_requests",
  "get_renderer_agent_input_state",
  "get_renderer_agent_input_navigation_state",
  "navigate_agent_input_notification",
  "capture_test_renderer",
  "cleanup_test_renderer_capture",
  "ensure_test_project",
  "archive_test_project",
  "create_test_chat",
  "open_test_chat",
  "create_test_orchestration_fixture",
  "create_test_orchestration",
  "get_test_orchestration",
  "mutate_test_orchestration",
  "archive_test_task",
  "archive_test_chat",
  "send_test_prompt",
  "mutate_project_provider_extension",
  "get_permission_state",
  "set_permission_default",
  "set_permission_change_behavior",
  "set_chat_permission",
  "preview_permission",
  "get_permission_ui_state",
  "control_permission_ui",
  "launch_test_run",
  "launch_harness_test_run",
  "list_codex_permission_requests",
  "reply_codex_permission_request",
  "inject_agent_input_request",
  "reply_agent_input_request",
  "reply_approval",
  "cancel_run",
  "wait_for_run",
] as const satisfies readonly DevMcpToolName[]

export const devMcpExposedTools = devMcpExposedToolNames.map((name) => {
  const tool = getDevMcpTool(name)
  if (!tool) throw new Error(`Missing dev MCP tool definition: ${name}`)
  return tool
})

export function isDevMcpToolName(name: string): name is DevMcpToolName {
  return getDevMcpTool(name) !== null
}
