// Single-instance dev launcher for Flapstack.
//
// Guarantees `npm run dev` always starts exactly ONE fresh dev instance on a
// known port, so you can never accidentally test stale code from an orphaned or
// duplicate dev server. It:
//   1. strips ELECTRON_RUN_AS_NODE - some IDE/agent shells export it, which
//      makes Electron boot as a bare Node process and crash the main process
//      with `Cannot read properties of undefined (reading 'isPackaged')`;
//   2. kills any stale Flapstack electron-vite / electron processes for THIS
//      checkout, plus stale packaged release apps generated by THIS checkout
//      (scoped by absolute path, never touches other repos/apps);
//   3. refuses to start - loudly - if the dev port is still occupied, instead
//      of silently falling back to :5174 and leaving two servers running;
//   4. launches `electron-vite dev`, forwarding signals and its exit code.
//
// Combined with `server.strictPort` in electron.vite.config.ts and the
// single-instance lock in src/main/index.ts, this makes a stale/duplicate local
// test instance impossible.

import { spawn, spawnSync } from "node:child_process"
import { existsSync } from "node:fs"
import net from "node:net"
import { resolve } from "node:path"
import { fileURLToPath } from "node:url"

const ROOT = resolve(fileURLToPath(new URL("..", import.meta.url)))
const LOCAL_ENV_FILE = resolve(ROOT, ".env.local")

// Local secrets are ignored by git. Load them only for the dev launcher, so
// the Electron main process and its OpenCode sidecar inherit the same values.
if (existsSync(LOCAL_ENV_FILE) && typeof process.loadEnvFile === "function") {
  process.loadEnvFile(LOCAL_ENV_FILE)
}

const DEV_PORT = Number(process.env.FLAPSTACK_DEV_PORT ?? 5173)
const IS_WIN = process.platform === "win32"
const sleep = (ms) => new Promise((r) => setTimeout(r, ms))

// Process patterns that identify a dev instance belonging to THIS checkout only
// (absolute-path scoped, so we never touch other repos, apps, or Electron tools).
const STALE_PATTERNS = [
  `${ROOT}/node_modules/.bin/electron-vite`,
  `${ROOT}/node_modules/electron-vite/bin/electron-vite.js`,
  `${ROOT}/node_modules/electron/dist`,
  `${ROOT}/release/.*/Flapstack.app/Contents/MacOS/Flapstack`,
]

// 1) Never let Electron run as a bare Node process.
delete process.env.ELECTRON_RUN_AS_NODE

function stalePids() {
  const found = new Set()
  for (const pattern of STALE_PATTERNS) {
    const res = spawnSync("pgrep", ["-f", pattern], { encoding: "utf8" })
    if (res.stdout) {
      for (const line of res.stdout.trim().split("\n")) {
        const pid = Number(line)
        if (pid && pid !== process.pid) found.add(pid)
      }
    }
  }
  return [...found]
}

// 2) Kill stale dev processes AND WAIT until they are actually gone before we
// launch. Waiting only on the port is not enough: the old Electron main can
// outlive its vite server, keep the single-instance lock + auth port, and force
// the new instance to quit - leaving an orphaned window running stale code.
async function killStaleAndWait() {
  if (IS_WIN) return // strictPort (below) still guards against conflicts on Windows
  let pids = stalePids()
  if (pids.length === 0) return
  console.log(`[dev] Stopping ${pids.length} stale Flapstack dev process(es)...`)
  for (const pid of pids) {
    try {
      process.kill(pid, "SIGTERM")
    } catch {}
  }
  const deadline = Date.now() + 3000
  while (Date.now() < deadline) {
    await sleep(200)
    if (stalePids().length === 0) {
      console.log("[dev] Stale instance stopped.")
      return
    }
  }
  // Escalate to SIGKILL for anything that ignored SIGTERM.
  for (const pid of stalePids()) {
    try {
      process.kill(pid, "SIGKILL")
    } catch {}
  }
  await sleep(400)
  pids = stalePids()
  if (pids.length) {
    console.error(`[dev] Could not stop stale process(es): ${pids.join(", ")}. Aborting.`)
    process.exit(1)
  }
  console.log("[dev] Stale instance stopped (forced).")
}

function portFree(port) {
  return new Promise((res) => {
    const srv = net.createServer()
    srv.once("error", () => res(false))
    srv.once("listening", () => srv.close(() => res(true)))
    srv.listen(port, "127.0.0.1")
  })
}

async function waitForPortFree(port, timeoutMs) {
  const deadline = Date.now() + timeoutMs
  do {
    if (await portFree(port)) return true
    await new Promise((r) => setTimeout(r, 250))
  } while (Date.now() < deadline)
  return portFree(port)
}

await killStaleAndWait()

if (!(await waitForPortFree(DEV_PORT, 4000))) {
  console.error(
    `\n[dev] Port ${DEV_PORT} is still in use after cleanup - refusing to start a` +
      ` second dev server on a different port.\n` +
      `[dev] Something outside this checkout is holding it. Free it and retry:\n` +
      `[dev]   lsof -ti :${DEV_PORT} | xargs kill -9\n`,
  )
  process.exit(1)
}

// 4) Launch electron-vite dev (run the bin's JS directly for cross-platform).
const bin = resolve(ROOT, "node_modules/electron-vite/bin/electron-vite.js")
const child = spawn(process.execPath, [bin, "dev"], {
  cwd: ROOT,
  stdio: "inherit",
  env: { ...process.env, FLAPSTACK_DEV_CHECKOUT: ROOT },
})
for (const sig of ["SIGINT", "SIGTERM"]) {
  process.on(sig, () => child.kill(sig))
}
child.on("exit", (code, signal) => {
  process.exit(code ?? (signal ? 1 : 0))
})
